### ISSUE TITLE
ASMOSESUTest fails

### ISSUE THREAD

**Issue by stellarspot** [singnet/asmoses#86]
The failed ASMOSESUTest:
```
In ASMOSESUTest::test_atomese_sr_3:
/ws/as-moses/tests/moses/main/ASMOSESUTest.cxxtest:100: Error: Test failed: unsupported (/ws/as-moses/opencog/combo/converter/combo_atomese.cc:142)
Failed 1 and Skipped 0 of 13 tests
```

**Comment by ngeiswei** [comment]
That's "normal", should be fixed within the next few days.

**Comment by vsbogd** [comment]
@ngeiswei, am I right that problem is that builtin::exp is not wrapped by atom yet?
May be disable test then?

**Comment by ngeiswei** [comment]
`exp` is now supported and it passes locally, but circleci seems to be the problem.

**Comment by vsbogd** [comment]
For me it doesn't pass locally.

**Comment by Bitseat** [comment]
Since the solution is not merged yet, it is failing as a result of unsupported functions in your case.

**Comment by vsbogd** [comment]
@Bitseat , thanks, so am I right that in current `singnet/asmoses` master it is not supported? 
If so should we just disable testcase until fix is merged?

**Comment by Bitseat** [comment]
yes you are right @vsbogd . <test_atomese_sr_3()> tests many of the ported asmoses units so we were trying so hard to have a full support of it instead of disabling it. But if is to much of a problem I guess disabling it for a while is a good idea.

**Comment by ngeiswei** [comment]
Or maybe we can just merge https://github.com/singnet/asmoses/pull/89 ? Though then it will pass locally but might still not pass on circleci for a reason we still don't understand.

**Comment by vsbogd** [comment]
Ah ok, so fix is raised as #89 , I didn't get it at the beginning. Yes, I see that locally test passes. It is strange that in CircleCI it fails with SIGSEGV.
